[project]
name = "radar-net"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.11.0.86",
    "torch>=2.6.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
